### ISSUE TITLE
Can't view dicom series

### ISSUE THREAD

**Issue by alexdaniel654** [openmiblab/pckg-wezel#39]
Having issues viewing a dicome series. I click File > Open then select the series I want to view then View > Series. This results in Wezel crashing with the following error message.
```
Traceback (most recent call last):
  File "/Users/rosa/.conda/envs/afirm/lib/python3.9/site-packages/wezel/core.py", line 189, in <lambda>
    self.triggered.connect(lambda: self.run(self.app))
  File "/Users/rosa/.conda/envs/afirm/lib/python3.9/site-packages/wezel/actions/view.py", line 45, in run
    app.display(series)
  File "/Users/rosa/.conda/envs/afirm/lib/python3.9/site-packages/wezel/apps/dicom.py", line 162, in display
    viewer = wezel.widgets.SeriesViewer(object)
  File "/Users/rosa/.conda/envs/afirm/lib/python3.9/site-packages/wezel/widgets/series_display.py", line 26, in __init__
    self.setData(series)
  File "/Users/rosa/.conda/envs/afirm/lib/python3.9/site-packages/wezel/widgets/series_display.py", line 90, in setData
    self._setImage()
  File "/Users/rosa/.conda/envs/afirm/lib/python3.9/site-packages/wezel/widgets/series_display.py", line 100, in _setImage
    self.brightness.setData(self.image)
  File "/Users/rosa/.conda/envs/afirm/lib/python3.9/site-packages/wezel/widgets/image_window.py", line 121, in setData
    self.setValue(center)
  File "/Users/rosa/.conda/envs/afirm/lib/python3.9/site-packages/wezel/widgets/image_window.py", line 151, in setValue
    self.spinBox.setValue(center)
TypeError: setValue(self, float): argument 1 has unexpected type 'NoneType'
Abort trap: 6
```

**Comment by plaresmedima** [comment]
Thank you for highlighting Alex.

Any chance you can send a dataset through so we can replicate? If it
happens with all series then just a single file might be enough.

**Comment by alexdaniel654** [comment]
Heres an example file.
[Test_Data.zip](https://github.com/QIB-Sheffield/wezel/files/9576913/Test_Data.zip)

**Comment by plaresmedima** [comment]
working in the current version
